// Place here the transaction data array. Use it in your application as needed.
const transactions = [
  {
    id: 1,
    type: 'income',
    category: 'salary',
    amount: 3000,
    description: 'Salary',
    date: '2025-01-15',
  },
  {
    id: 2,
    type: 'expense',
    category: 'housing',
    amount: 1200,
    description: 'Rent',
    date: '2025-01-01',
  },
  {
    id: 3,
    type: 'expense',
    category: 'food',
    amount: 450,
    description: 'Groceries',
    date: '2025-01-10',
  },
  {
    id: 4,
    type: 'income',
    category: 'side-income',
    amount: 700,
    description: 'Freelance',
    date: '2025-01-20',
  },
  {
    id: 5,
    type: 'expense',
    category: 'bills',
    amount: 300,
    description: 'Utilities',
    date: '2025-01-05',
  },
  {
    id: 6,
    type: 'expense',
    category: 'transport',
    amount: 120,
    description: 'Public transport',
    date: '2025-01-12',
  },
  {
    id: 7,
    type: 'expense',
    category: 'entertainment',
    amount: 200,
    description: 'Cinema & dinner',
    date: '2025-01-18',
  },
  {
    id: 8,
    type: 'income',
    category: 'bonus',
    amount: 400,
    description: 'Performance bonus',
    date: '2025-01-25',
  },
  {
    id: 9,
    type: 'expense',
    category: 'health',
    amount: 90,
    description: 'Pharmacy',
    date: '2025-01-08',
  },
  {
    id: 10,
    type: 'expense',
    category: 'shopping',
    amount: 250,
    description: 'Clothes',
    date: '2025-01-22',
  },
  {
    id: 11,
    type: 'income',
    category: 'gift',
    amount: 150,
    description: 'Birthday gift',
    date: '2025-01-28',
  },
  {
    id: 12,
    type: 'expense',
    category: 'food',
    amount: 80,
    description: 'Restaurant',
    date: '2025-01-27',
  },
];

module.exports = transactions;
